# grid_search:
#   class: GridSearchCV
#   module: sklearn.model_selection
#   params:
#     cv: 3
#     verbose: 3
#     n_jobs: -1
# model_selection:
#   module_0:
#     class: RandomForestRegressor
#     module: sklearn.ensemble
#     params:
#       n_estimators: 100 
#       max_depth: 10
#     search_param_grid:
#       n_estimators:
#       -  50
#       - 100
#       - 200
#       max_depth:
#       - 0
#       - 10
#       - 20
#   module_1:
#     class: CatBoostRegressor
#     module: catboost
#     params:
#       iterations: 3
#       learning_rate: 0.1
#       depth: 100
#     search_param_grid:
#       iterations:
#       - 2
#       - 3
#       - 4
#       learning_rate:
#       - 0.1
#       - 0.01
#       - 0.05
#       depth:
#       - 100
#       - 50
#       - 150


grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 1
model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 200
      criterion: squared_error
    search_param_grid:
      n_estimators:
      - 150
      - 200
      - 250
      max_depth:
      - 2
      - 5
      - 6
    module_1:
        class: SVR
        module: sklearn.svm
        params:
          kernel: rbf
        search_param_grid:
          kernel:
          - poly
          - rbf